#!/bin/bash

terminalColors() {
	# Colors from - https://gist.github.com/5682077.git
	TC='\e['

	Bold="${TC}1m"    # Bold text only, keep colors
	Undr="${TC}4m"    # Underline text only, keep colors
	Rst="${TC}0m"     # Reset all coloring and style

	# Basic colors
	Black="${TC}30m"
	Red="${TC}31m"
	Green="${TC}32m"
	Yellow="${TC}33m"
	Blue="${TC}34m"
	Purple="${TC}35m"
	Cyan="${TC}36m"
	White="${TC}37m"

	Crossed="\u2718"

	#copy pasted tick symbold because unicode was acting weird
	Ticked="✓"
	Info="!"

	Oper=${Bold}'[ * ]'
	OperSuccess=${Bold}${Green}'[ '${Ticked}' ]'
	OperFailed=${Bold}${Red}'[ '${Crossed}' ]'
	Info=${Bold}${Yellow}'[ '${Info}' ]'
}

printNormal() {
	echo -e "${Oper} $1$Rst";
}

printSuccess() {
	echo -e "${OperSuccess} $1$Rst"
}

printFailed() {
	echo -e "${OperFailed} $1$Rst"
}

printInfo() {
	echo -e "${Info} $1$Rst"
}

help() {
	echo -e "${Bold}Usage:${Rst}\neasy-apache [options]\n\n${Bold}Options:${Rst}\n-f | --full:\t\tFull setup, default option if none is provided\n-a | --apache:\t\tAdding new site (includes apache install)\n-s | --SSL:\t\tInstall SSL certificate for sites available\n-h | --help:\t\tHelp (shows available commands)\n-v | --version:\t\tCheck easy-apache version${Rst}"
	echo -e "\n${Bold}Example\n${Rst}easy-apache -f\t\t\t#for full installation i.e Apache & SSL certificate\neasy-apache --full\t\t#for full installation i.e Apache & SSL certificate\neasy-apache -a\t\t\t#for installating Apache server\neasy-apache -s\t\t\t#for installating SSL certificate"
}

version() {
	echo "0.1 Alpha"
}

install() {

	# $1 is the argument
	# $2 is the font name
	
	fontName=${2,,}

	if [[ -z $fontName ]]
	then
		printFailed "You need to specify font name to be installed"
		printNormal "Example, gfinstall montserrat"
		return
	fi

	if ! grep -Fxq "$fontName" gflist
	then
		printFailed "Can't find font $fontName "
		printNormal "Check if the font name is correct"
		printNormal "Run \`gfinstall --update\` and then try installing the font"
		return
	fi

	printNormal "Downloading $fontName from Google Fonts..."
	svn export https://github.com/google/fonts/trunk/ofl/$fontName /var/tmp/gfFonts --force &> /dev/null

	if [[ -z $1 ]]
	then
		printNormal "Installing font for all users"
		mv /var/tmp/gfFonts/*.ttf /usr/share/fonts/
		rm -r /var/tmp/gfFonts
		printSuccess "$fontName Installed"
		return
	fi

	if [[ $1 == "-l" ]]
	then
		printNormal "Installing font for all users"
		mv /var/tmp/gfFonts/*.ttf ~/.fonts
		rm -r /var/tmp/gfFonts
		printSuccess "$fontName Installed"
		return
	fi

	printFailed "Probably invalid argument, type \`gfinstall --help\` to know all commands"
}

terminalColors
if [ "$1" != "" ]
then
    PARAM=$1
    case $PARAM in
        -h | --help      ) help; exit;;
		-v | --version   ) version; exit;;
		-l | --local	 ) install "-l" $2; exit;;
                        *) install "" $1; exit;;
    esac
fi
help