#!/bin/bash

# make sure to install jq before doing the update
# sudo apt install jq or sudo snap install jq

fonts_api=$(echo `curl "https://api.github.com/repos/google/fonts/contents/ofl" | jq '.[]'`)

echo $fonts_api | jq -r .name > gflist.txt
echo "Done"