#!/bin/bash

# This script updates gflist with all google fonts available
# to use this you must set GOOGLE_API_KEY env variable

# Explanation for below code
# line 13 we get data from the api and store it in $apiData
# line 14 echo ${apiData,,} will convert everything to lowercase
#       - jq -r is responsible for parsing api data (keep in mind that all data have been lowered before parsing,
#         might be bad but it stays till I find better solution)
#       - tr -d ' ' will get rid of all the spaces in between names and write the output to the file gflist

apiData=`curl -s "https://www.googleapis.com/webfonts/v1/webfonts?key=$GOOGLE_API_KEY&sort=alpha"`
echo ${apiData,,} | jq -r '.items[].family' | tr -d ' ' > gflist
echo "Update done"