.TH "gfinstall" 1
.SH NAME
gfinstall \- GFInstall is a google font installer. You can install google fonts directly from your terminal.
.SH SYNOPSIS
.B gfinstall
[OPTIONS]
.SH DESCRIPTION
.PP
GFInstall is a google font installer. You can install google fonts directly from your terminal. GFInstall helps you install any google font using just terminal, it downloads specified font from google fonts and installs it on your system either globally or locally.
.SH OPTIONS
.TP
.BR \-l ", " \-\-local
To Install fonts locally
.TP
.BR \-v ", " \-\-version
Check gfinstall version
.TP
.BR \-ul ", " \-\-update-list
Updates google fonts list
.TP
.BR \-h ", " \-\-help
Displays available options
.SH EXAMPLES
.TP
.BR gfinstall " " montserrat 
# installs montserrat font globally
.TP
.BR gfinstall " " \--local
# install ubuntu font locally
.TP
.BR gfinstall " " \-v
# to check gfinstall version
.SH AUTHORS
.PP
(C) Copyright 2020 R Pavan Kumar <realpvn@gmail.com>
.PP
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH BUGS
Report bugs on the github repo for gfinstall (https://github.com/realpvn/gfinstall). Open a issue and I will reply/fix as soon as I can.
.SH CONTRIBUTE
.PP
You can contribute to gfinstall here - https://github.com/realpvn/gfinstall. If your contributions are good/big your name might be added to AUTHORS section