.TH "gfinstall" 1
.SH NAME
gflist_update \- It wil update the font lists in gflist
.SH SYNOPSIS
.B gflist_update
[OPTIONS]
.SH DESCRIPTION
.PP
It will update the font lists in gflist. Gflist is used to minimise api calls, gflist is a list of google fonts so before downloading google font for download we can verify if that font exist.
.SH EXAMPLES
.TP
.BR gflist_update
# to update gflist
.SH AUTHORS
.PP
(C) Copyright 2020 R Pavan Kumar <realpvn@gmail.com>
.PP
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH BUGS
Report bugs on the github repo for gfinstall (https://github.com/realpvn/gfinstall). Open a issue and I will reply/fix as soon as I can.
.SH CONTRIBUTE
.PP
You can contribute to gfinstall here - https://github.com/realpvn/gfinstall. If your contributions are good/big your name might be added to AUTHORS section