#!/bin/bash

set -e

echo "Source gflist"
echo 'source /usr/share/bash-completion/completions/gfinstall/gflist-completion' >> ~/.bashrc
source /usr/share/bash-completion/completions/gfinstall/gflist-completion

#DEBHELPER#

exit 0