#!/bin/bash

set -e

echo 'source /usr/share/bash-completion/completions/gfinstall/gfinstall-completion.bash' >> ~/.bashrc
. /usr/share/bash-completion/completions/gfinstall/gfinstall-completion.bash
echo "done"

#DEBHELPER#

exit 0